server:  
    port: 8080
    servlet: 
       session.timeout: 60000
       contextpath: /ibike    
    undertow:  
        io-threads: 16  
        worker-threads: 256  
        buffer-size: 1024  
        buffers-per-region: 1024  
        direct-buffers: true 
logging:
    level.root: info
    level.org.springframework: info
    level.com.aa: info
    file: /tmp/aa.log
swagger: 
    enabled: false